### ISSUE TITLE
Documentation API Enedis/Linky

### ISSUE THREAD

**Issue by SimonMellerin** [KiboOst/php-LinkyAPI#1]
Bonjour,

Je voudrais m'inspirer de ton travail sur la récupération des données Linky, je voulais savoir si tu avais trouvé une documentation de l'API côté Enedis/Linky, j'ai beau chercher, je n'en trouve pas sur leur site..

Merci !

**Comment by Xanatos00** [comment]
On a tous eu plus ou moins le même problème.
Regarde du côté des README des différents projets tagués linky & enedis sur github

**Comment by KiboOst** [comment]
Il y a une API Enedis en effet:
https://data.enedis.fr/api/v1/documentation

Mais vue tous les problèmes qu'ils ont avec leurs serveurs (çà fait 5jours que je n'ai plus aucune données), se baser sur une API à eux me parait un peu risqué ...

**Comment by Xanatos00** [comment]
Oui, sauf que ce n'est pas celle utilisée par espace-client-particuliers.enedis.fr
Il me semble bien que cela concerne beaucoup de choses à propos de la distribution chez Enedis, mais pas les consommations clients.

**Comment by KiboOst** [comment]
Ah je ne savais pas, je ne l'ai pas trop regardé.
A ma connaissance rien d'autre, pour çà que j'ai fais mon API perso...

**Comment by SimonMellerin** [comment]
OK ok, merci pour vos réponse, mais du coup, pour faire ton API @KiboOst tu les as trouvé où tes infos ?

**Comment by KiboOst** [comment]
Nulle part, j'ai tout fait à la mano en me basant sur leur site et en automatisant çà.

**Comment by SimonMellerin** [comment]
Ok, merci, je vais récupérer ce que tu as fait alors :)

Pour info, j'essaye de faire un petite web app en symfony pour analyser les données d'un linky avec la météo observée (récupérée sur Météo France)

Mon but final étant de la packager pour YUNOHost

**Comment by Xanatos00** [comment]
Sympa,
attention, les données ne sont disponibles que à J-1.
Un autre readme https://github.com/PhilBri/Node-Linky/blob/master/README.md

**Comment by SimonMellerin** [comment]
> les données ne sont disponibles que à J-1
ça veut dire que je peux récupérer uniquement les données de consommation d'hier et d'aujourd'hui ?
ça devrait pas trop me poser problème, je comptais les collecter quotidiennement

Merci pour la ressource

**Comment by KiboOst** [comment]
Non, tu peux collecter ce que tu jusqu'à hier. Les données d'aujourd'hui deviendront dispo demain (vers 8h quand tout va bien), et ainsi de suite

**Comment by Xanatos00** [comment]
Voilà, désolé je me suis mal exprimé.
Il y a un certain nombre de limitations. Celles que j'ai repérées:              
* API doesn't provide the current day 
* API is under maintenance between 23:00 and 02:00                     
date format: DD/MM/AAAA               
hour format: hours are half hour...   
period limitations:                   
* YEAR: any selector                  
* MONTH: max 12 months                
* DAY: max 31 days                    
* HOUR: min 2 days, max ?

**Comment by SimonMellerin** [comment]
Ok merci pour tous vos renseignements, ça va bien m'aider !

**Comment by MathieuLorber** [comment]
Un peu tard mais pour ceux qui passeront par là par un moteur de recherche => https://datahub-enedis.fr/data-connect/

**Comment by greg-ware** [comment]
@MathieuLorber , par contre:
_Les clients résidentiels ne pourront pas utiliser l’API Data Connect pour accéder à leurs données et pourront les consulter et les télécharger dans leur compte : https://mon-compte-particulier.enedis.fr/._

**Comment by Xanatos00** [comment]
open data, mais pas trop non plus...
merci pour l'info @greg-ware 
le webscraping a encore de beaux jours, surtout quand on voit la régression de l'IHM de Enedis pour afficher les données.

**Comment by SimonMellerin** [comment]
Enedis a ajouté recaptcha au login sur son nouveau site, le scraping va pas être aussi simple...

**Comment by sgrillon14** [comment]
> https://datahub-enedis.fr/data-connect/

this Web site API have "NET::ERR_CERT_REVOKED"

**Comment by MathieuLorber** [comment]
on peut discuter api, pour ceux qui veulent récupérer leur donnée perso
