### ISSUE TITLE
__ERROR__: Unknown SSL protocol error in connection to espace-client-particuliers.enedis.fr:443 

### ISSUE THREAD

**Issue by aussitot** [KiboOst/php-LinkyAPI#2]
Bonjour,
Le script fonctionne toujours ?
J'ai une erreur : __ERROR__: Unknown SSL protocol error in connection to espace-client-particuliers.enedis.fr:443 
et j'avoue ne pas trouver le soucis.

**Comment by KiboOst** [comment]
Bonjour,

Avez vous résolu le problème ?
Je n'ai pas relevé de soucis de mon coté, cela dit le serveur enedis est souvent parterre. çà peux aussi venir de la config ssl de votre serveur, notamment le certificat ssl utilisé.

**Comment by aussitot** [comment]
Bonjour,
Oui ca fonctionne 👍 
A vrai dire je n’ai rien fait de particulier :)
Merci pour le script et bravo (c’est tres propre)

**Comment by KiboOst** [comment]
Merci. Sans doute les serveurs enedis alors, çà arrive régulièrement ...
