### ISSUE TITLE
Problème avec le script

### ISSUE THREAD

**Issue by SatanasSeb** [KiboOst/php-LinkyAPI#5]
Bonjour KiboOst,

Je suis en train de travailler sur une récupération de données sur des linky, mais j'ai quelques erreurs lorsque je lance le linkyCron.php, j'obtiens :

`Warning: Invalid argument supplied for foreach() in /var/www/html/linky/phpLinkyAPI.php on line 60`
`Warning: Invalid argument supplied for foreach() in /var/www/html/linky/phpLinkyAPI.php on line 86`
`Warning: DateTime::modify(): Failed to parse time string (- -1 year) at position 0 (-): Unexpected character in /var/www/html/linky/phpLinkyAPI.php on line 114`
`Warning: Invalid argument supplied for foreach() in /var/www/html/linky/phpLinkyAPI.php on line 115`
`Notice: Undefined index: Oct 2019 in /var/www/html/linky/linkyCron.php on line 32`
`Notice: Undefined offset: 2019 in /var/www/html/linky/linkyCron.php on line 47`
`Notice: Undefined index: 09/10/2019 in /var/www/html/linky/linkyCron.php on line 72`

Et mon Json est vide...

Est-ce que Enedis possède toujours la même arborescence pour aller chercher les données? car les données sont affichées dans https://espace-client-particuliers.enedis.fr/group/espace-particuliers/mes-donnees-de-production-prod et l'url que tu as mis dans le code pointe vers /suivi-de-consommation, mais le changer ne fonctionne pas non plus.
As-tu modifié ton code depuis la création?

Merci de ton aide

**Comment by KiboOst** [comment]
Bonjour,

Ces erreurs viennent du fait que le server enedis ne répond pas ou ne renvoit pas les bonnes données.
Je viens d'ajouter des check dans les fonctions, les _data['days'] etc son null dans ce cas, et il suffit de checker çà.
